### ISSUE TITLE
Additional Homework Info

### ISSUE THREAD

**Issue by Arya766** [hw-manager/android#16]
Most of the times, there are others involved in a homework; it would be nice if there were a "note" option for each homework, that users could enter these extra infos in it.
when adding this, please add an option to show/hide notes.

**Comment by AltNico** [comment]
Good idea, maybe an extra page for each homework is a good idea?

I think of something like this:
All homework in the main list, like at the moment, and only the subject, the title, the date and important/urgent/whatever is shown. If you tap on one item, it opens a new screen with information to that homework in more detail. From this view you could also edit or delete the homework.
How do you think? @Arya766 @easyaspi314

**Comment by Arya766** [comment]
I think it would be better if it rolled down, and not opened a new screen; just roll down and show extra info, but, if the users want to edit, then  they have to bear new screen. So, tap to roll down, and long tap to edit is what I think. I myself am so fed up with too many new screens in almost all android apps.

**Comment by easyaspi314** [comment]
ExpandableListView?

**Comment by Arya766** [comment]
@easyaspi314 yes I guess.

**Comment by AltNico** [comment]
@easyaspi314 Yes, I think, that's the best way.
