### ISSUE TITLE
Save time in milliseconds

### ISSUE THREAD

**Issue by AltNico** [hw-manager/android#18]
At the moment, the time is saved as a string when the user creates the homework.
It would be better, if the time is saved in milliseconds and convert to a string when loading the homework list.
This would make it possible to sort the homework list and change the date format when changing the language.

**Comment by easyaspi314** [comment]
Yes, then we can set the adapter to use the date because I ran into an issue where I saw an entry that was formatted to the wrong date.

**Comment by easyaspi314** [comment]
Should we use SQLite's date tools instead?
https://www.sqlite.org/lang_datefunc.html

**Comment by AltNico** [comment]
You can try to implement it, I've never heard from it.
