### ISSUE TITLE
No update for Translations!

### ISSUE THREAD

**Issue by Arya766** [hw-manager/android#22]
@AltNico  there have been some changes, and there must be new words to translate, but the crowdin project hasn't changed.

**Comment by AltNico** [comment]
You should have received an e-mail, I've updated them just now.

**Comment by Arya766** [comment]
Done!

**Comment by AltNico** [comment]
Thank you!

**Comment by Arya766** [comment]
You are very welcome.

**Comment by Arya766** [comment]
@AltNico I was bored ... so I did the Arabic translation too! Remember to add to the next version!

**Comment by AltNico** [comment]
Thank you, very nice!

**Comment by Arya766** [comment]
Any time.

**Comment by Arya766** [comment]
Et voilà! French is done! That's my limit. No more languages.
