### ISSUE TITLE
Branches

### ISSUE THREAD

**Issue by AltNico** [hw-manager/android#5]
@easyaspi314 Please do not push to master, always to another (new) branch.
It would be good if I have something to contact you, like a mail-address. You can find mine on my GitHub page.

**Comment by easyaspi314** [comment]
I am sending you an email with my email address. Thanks for push access. :)

**Comment by easyaspi314** [comment]
I have added two branches for main stuff, one for me and one for you.

**Comment by AltNico** [comment]
OK, thanks.
